import type { MetadataRoute } from "next";

/**
 * The Frontdesk's installable PWA manifest. `display: standalone` is what a
 * desk machine gets — an app window, not a browser tab — and `start_url` is
 * the desk itself, so a relaunch from the home screen goes straight to work
 * (spec/applications.md §3, spec/offline-sync.md §1).
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Silid Frontdesk",
    short_name: "Silid Desk",
    description: "Offline-first front desk for hotel operations",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "any",
    background_color: "#ffffff",
    theme_color: "#09090b",
    icons: [
      {
        // Generated by ImageResponse at request time, not a checked-in binary:
        // see src/app/icons/icon-192/route.tsx.
        src: "/icons/icon-192",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-512",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
